import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.*;

/**
 *
 * @author Alican
 */
public class TakimSayisiveIsmi extends javax.swing.JFrame {

    /**
     * Creates new form TakimSayisiveIsmi
     */
    private int takimSayisi; //takimSayisi değişkeni takım sayısını tutacak.
    private String[] takimIsimleri; //takimIsimleri ise takım isimlerini içeren bir dizi olacak.
     
    public TakimSayisiveIsmi() {
        
        initComponents();
        setTitle("Takım Sayısı Formu"); //arayüzün başlık metnini ayarlıyoruz.
        setLocationRelativeTo(null); //Form'un tam ortada olmasını sağlar.
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        lb1.setText("Takım sayısı giriniz : ");

        btn1.setText("TAKIM SAYISINI AL ");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
      
      
        String kontrol = text1.getText(); //text1'e boş giriş yapılmasını önlemek için kontrol yapıyoruz.
        if (!kontrol.isEmpty())
        {
           try {
               
           
            takimSayisi = Integer.parseInt(text1.getText()); //Kullanıcıdan takım sayısını alırken geçerlilik kontrolü yaparız. Eğer geçerli bir sayı girilmişse, takım sayısını takimSayisi değişkenine atarız.
            takimIsimleri = new String[takimSayisi]; //Takım sayısı örneğin 4 ise takimIsimleri dizisi 4 elemanlı olur.
            boolean isimlerAyni = false; // Takım isimlerinin aynı olup olmadığını kontrol etmek için bir bayrak değişkeni
            for (int i = 0; i < takimSayisi; i++)  //For döngüsü takım isimlerini almak için ve takimSayisi kadar döner.
            {
                String takimIsmi = JOptionPane.showInputDialog(null, "Takım " + (i+1) + " ismini girin:", "Takım Adları", JOptionPane.QUESTION_MESSAGE);

                if (takimIsmi == null || takimIsmi.isEmpty()) //Kullanıcı takimIsmi'ni boş girmişse takım ismi boş bırakılamaz hatası verir.
                {
                    // Boş değer veya "Cancel" seçildiği için hata ver
                    JOptionPane.showMessageDialog(null, "Takım ismi boş bırakılamaz. Lütfen tekrar deneyin.");
                    i--; // Bu takımı tekrar yapmak için i'yi azalt
                    continue;
                }
                if (i > 0)
                {
                    // Daha önce girilen takım isimlerini kontrol et
                    for (int j = 0; j < i; j++)
                    {
                        if (takimIsmi.equals(takimIsimleri[j])) 
                        {
                            isimlerAyni = true;
                            break;
                        }
                    }
                }

                if (isimlerAyni)
                {
                    JOptionPane.showMessageDialog(null, "Takım isimleri aynı olamaz. Lütfen tekrar deneyin.");
                    isimlerAyni = false; // Bayrağı sıfırla
                    i--;
                    continue;
                }

                takimIsimleri[i] = takimIsmi; //girilen takımların isimlerini takimIsimleri[0],takimIsimleri[1],... şeklinde sırasıyla dizinin elemanı olarak içine atar.
            }

            text1.setText(""); //text1'i temizler.
            dispose(); //açık olan TakimSayisiveIsmi formunu kapatır.

            TakimlariGorme takimlar = new TakimlariGorme(takimIsimleri, takimSayisi); //TakimlariGorme formuna geçiş yapmak için bir nesne oluşturur ve TakimlariGorme formuna takimIsimleri, takimSayisi değişkenlerini gönderir.
            takimlar.setVisible(true); //TakimlariGorme formunu görünür yapar yani açar.
         } 
            catch (NumberFormatException e)
            {
               JOptionPane.showMessageDialog(null, "Geçersiz sayı formatı!", "Hata", JOptionPane.ERROR_MESSAGE); //sayı haricinde ne girilirse girilsin geçersiz sayı formatı diye hata verir.
            }    
        }       
        else 
        {
            JOptionPane.showMessageDialog(null, "Geçersiz sayı formatı!", "Hata", JOptionPane.ERROR_MESSAGE); //Eğer text1'e boş giriş yapılıp takım sayısı al butonuna tıklanırsa hata verir.
        }
          
        

    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakimSayisiveIsmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakimSayisiveIsmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakimSayisiveIsmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakimSayisiveIsmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakimSayisiveIsmi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JLabel lb1;
    private javax.swing.JTextField text1;
    // End of variables declaration//GEN-END:variables
}
