
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alican
 */
public class TakimlariGorme extends javax.swing.JFrame {

    /**
     * Creates new form TakimlariGorme
     */
    private String[] sutunBasliklari = {"Takımlar"}; //Table için sütunda başlık oluşturmak için tek boyutlu dizinin içine "Takımlar" başlığını atadım.
    private String [][] takimIsimleri; //TakimSayisiveIsmi dizisini tanımladım, önceki TakimSayisiveIsmi formundan takimIsimlerini alabilmek için.
    private int takimSayisi; //Önceki TakimSayisiveIsmi formundan takimSayisini alabilmek için tanımlama yaptım.
    
    public TakimlariGorme(String[] takimIsimleri, int takimSayisi) { //Bu yapıcı metot, TakimlariGorme sınıfının bir nesnesi oluşturulduğunda otomatik olarak çağrılır. 
        initComponents();
        setTitle("Takımları Görme ve Müsabaka Oluşturma"); //Form'un başlığını belirledim.
        setLocationRelativeTo(null); //Form'un tam ortada olmasını sağlar.
        this.takimSayisi = takimSayisi; //this.takimSayisi = takimSayisi; ifadesiyle, alınan takimSayisi değeri sınıfın takimSayisi özelliğine atanır.
        this.takimIsimleri = new String[takimIsimleri.length][1]; //this.takimIsimleri = new String[takimIsimleri.length][1]; ifadesiyle, takimIsimleri dizisinin boyutuyla uyumlu bir 2 boyutlu String dizisi oluşturulur. Bu dizi, takım isimlerini depolamak için kullanılır.
        for (int i = 0; i < takimIsimleri.length; i++)
        {
            this.takimIsimleri[i][0] = takimIsimleri[i]; //for döngüsü kullanılarak, takimIsimleri dizisindeki her takım ismi, takimIsimleri özelliğinin ilgili elemanına atanır. Bu işlem, her takım ismini tek sütunlu bir 2 boyutlu dizide saklamayı sağlar.
        }
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table1);

        btn1.setText("Müsabaka Oluştur");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("GERİ");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(btn2)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        DefaultTableModel model = new DefaultTableModel(takimIsimleri,sutunBasliklari); //Takımlar Tablosunda takimIsimleri yani data'yı ve kolon adlarının ne olacağını belirledim.
        table1.setModel(model); // JTable bileşenine veri modelini atadım.
       
    }//GEN-LAST:event_formWindowActivated

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed

          dispose(); //TakimlariGorme formunu kapatır.
          Musabakalar musabaka = new Musabakalar(takimIsimleri); //Musabakalar formuna geçiş yapmak için bir nesne oluşturur ve Musabakalar formuna takimIsimleri değişkenlerini gönderir.
          musabaka.setVisible(true); //Musabakalar formunu görünür kılar yani açar.
          
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        
        dispose(); //TakimlariGorme formunu kapatır.
        TakimSayisiveIsmi geri =  new TakimSayisiveIsmi(); //TakimSayisiveIsmi formuna geri geçiş yapmak için bir nesne oluşturur.
        geri.setVisible(true); //TakimSayisiveIsmi formunu görünür kılar yani açar.
        
    }//GEN-LAST:event_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String [] takimIsimleri,int takimSayisi) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakimlariGorme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakimlariGorme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakimlariGorme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakimlariGorme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakimlariGorme(takimIsimleri,takimSayisi).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
